In [5]:
import pandas as pd
# from pandas import Series, DataFrame




row_of_data = [10,20,30,40]
cols= ["Nate", "Rebecca", "Edwin", "Preston"]
series_of_data = pd.Series(row_of_data, index=cols)
print(f"list: {row_of_data}")
print(f"series: \n{series_of_data}")

list: [10, 20, 30, 40]
series:
Nate       10
Rebecca    20
Edwin      30
Preston    40
dtype: int64

In [6]:
# DataFrame By column

family = {
    "name": ["nate", "rebecc", "edwin", "preston"],
    "age": [40, 41, 12, 8]
}
df1 = pd.DataFrame(data=family, index=family["name"])
df1

            name  age
nate        nate   40
rebecc    rebecc   41
edwin      edwin   12
preston  preston    8

In [7]:
# DataFrame by Rows
cols1 = ["name", "age"]
rows = [
    ["nate", 40],
    ["rebecca", 41],
    ["edwin", 12],
    ["preston", 8],
]
df2 = pd.DataFrame(data=rows, columns=cols1)
df2

      name  age
0     nate   40
1  rebecca   41
2    edwin   12
3  preston    8

In [8]:
df1["age"]["nate"]

np.int64(40)

In [9]:
df2["name"][1]

'rebecca'

In [10]:
df2["gender"] = ["M", "F", "M", "M"]
df2

      name  age gender
0     nate   40      M
1  rebecca   41      F
2    edwin   12      M
3  preston    8      M

In [11]:
df2[["name", "gender"]]

      name gender
0     nate      M
1  rebecca      F
2    edwin      M
3  preston      M

In [12]:
df2.columns

Index(['name', 'age', 'gender'], dtype='str')

In [13]:
df2.head(2)

      name  age gender
0     nate   40      M
1  rebecca   41      F

In [15]:
df2.isnull().sum()

name      0
age       0
gender    0
dtype: int64

In [16]:
df2.describe()

             age
count   4.000000
mean   25.250000
std    17.689451
min     8.000000
25%    11.000000
50%    26.000000
75%    40.250000
max    41.000000

In [17]:
df1.sort_index(ascending=False, inplace=True)

In [18]:
df1 = df1.sort_values(["age"])

In [19]:
df1

            name  age
preston  preston    8
edwin      edwin   12
nate        nate   40
rebecc    rebecc   41

In [20]:
df2 = df2.rename(columns={"age": "a"})
df2

      name   a gender
0     nate  40      M
1  rebecca  41      F
2    edwin  12      M
3  preston   8      M

In [21]:
df2.loc[0]

name      nate
a           40
gender       M
Name: 0, dtype: object

In [22]:
df2.loc[0,"a"]

np.int64(40)

In [23]:
df2.loc[0,"a"] = 39
df2

      name   a gender
0     nate  39      M
1  rebecca  41      F
2    edwin  12      M
3  preston   8      M

In [24]:
df1.loc["nate", "age"]

np.int64(40)

In [25]:
df1.iloc[0,1]

np.int64(8)

In [26]:
df1 = df1.reset_index()

In [27]:
df1.drop(labels=["index"], axis=1)

      name  age
0  preston    8
1    edwin   12
2     nate   40
3   rebecc   41

In [28]:
df2.at[0, "a"]

np.int64(39)

In [29]:
df2.iat[1,1] = 39

In [30]:
df2

      name   a gender
0     nate  39      M
1  rebecca  39      F
2    edwin  12      M
3  preston   8      M

In [31]:
df2.loc[0:3, "name"]

0       nate
1    rebecca
2      edwin
3    preston
Name: name, dtype: str

In [32]:
df2.loc[:,"name"]

0       nate
1    rebecca
2      edwin
3    preston
Name: name, dtype: str

In [33]:
df2.loc[df2["a"]>=18]

      name   a gender
0     nate  39      M
1  rebecca  39      F

In [34]:
df2.loc[df2["a"]>=18, "name"]

0       nate
1    rebecca
Name: name, dtype: str

In [35]:
df2["is_adult"] = False
df2

      name   a gender  is_adult
0     nate  39      M     False
1  rebecca  39      F     False
2    edwin  12      M     False
3  preston   8      M     False

In [36]:
df2.loc[df2["a"] >= 18, "is_adult"] = True
df2

      name   a gender  is_adult
0     nate  39      M      True
1  rebecca  39      F      True
2    edwin  12      M     False
3  preston   8      M     False